# Generated by Django 4.2.4 on 2023-08-05 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabpannel',
            name='members',
        ),
        migrations.AddField(
            model_name='collabpannel',
            name='members',
            field=models.ManyToManyField(through='Notes.CollabPannelMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
