# Generated by Django 4.2.3 on 2023-08-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='auhtor',
        ),
        migrations.CreateModel(
            name='CollabPannel',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Notes.notes')),
            ],
            options={
                'db_table': 'NoteGroup',
            },
        ),
    ]
