# Generated by Django 4.2.4 on 2023-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_collabpannel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='remind_user',
            field=models.BooleanField(default=False),
        ),
    ]
