# Generated by Django 4.2.4 on 2023-08-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_notes_remind_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='scope',
            field=models.IntegerField(default=2),
        ),
    ]
