# Generated by Django 4.2.4 on 2023-08-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notes_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created']},
        ),
    ]
